SELECT company_name, deadline, job_title, recruit_url, crawling_time, 'saramin' AS source_table
FROM (
    SELECT company_name, deadline, job_title, recruit_url, keywords, experience, crawling_time,
           LAG(company_name, 1) OVER (ORDER BY crawling_time DESC) AS prev_company
    FROM saramin
    WHERE (STR_TO_DATE(saramin.deadline, '%Y-%m-%d') > CURDATE() OR saramin.deadline = '채용시 마감')
        AND (saramin.experience = "신입" OR saramin.experience = "무관(신입포함)")
    ORDER BY crawling_time DESC
) AS saramin_data
WHERE (((saramin_data.job_title LIKE "%웹 기획%") OR (saramin_data.job_title LIKE "%앱 기획%") OR (saramin_data.job_title LIKE "%서비스 기획%") OR (saramin_data.job_title LIKE "%콘텐츠 기획%") OR (saramin_data.job_title LIKE "%전략 기획%") OR (saramin_data.job_title LIKE "%프로덕트 매니저%")) AND ((saramin_data.job_title NOT LIKE "%창업%")AND(saramin_data.job_title NOT LIKE "%번역%")AND(saramin_data.job_title NOT LIKE "%석사%")AND(saramin_data.job_title NOT LIKE "%박사%")AND(saramin_data.job_title NOT LIKE "%코드잇%")AND(saramin_data.job_title NOT LIKE "%교육생%")AND(saramin_data.job_title NOT LIKE "%국비%")AND(saramin_data.job_title NOT LIKE "%청년수당%")AND(saramin_data.job_title NOT LIKE "%제약%")AND(saramin_data.job_title NOT LIKE "%건설%")AND(saramin_data.job_title NOT LIKE "%연구%")AND(saramin_data.job_title NOT LIKE "%기계%")AND(saramin_data.job_title NOT LIKE "%행정%")AND(saramin_data.job_title NOT LIKE "%호텔%")AND(saramin_data.job_title NOT LIKE "%천재교육%")AND(saramin_data.job_title NOT LIKE "%천재교과서%")AND(saramin_data.job_title NOT LIKE "%SeSAC%")AND(saramin_data.job_title NOT LIKE "%APM%")AND(saramin_data.job_title NOT LIKE "%apm%")AND(saramin_data.job_title NOT LIKE "%edi%")AND(saramin_data.job_title NOT LIKE "%EDI%")AND(saramin_data.job_title NOT LIKE "%개발자%")AND(saramin_data.job_title NOT LIKE "%시공%")AND(saramin_data.job_title NOT LIKE "%유튜브%")AND(saramin_data.job_title NOT LIKE "%양성%")) AND ((saramin_data.company_name NOT LIKE "%창업%")AND(saramin_data.company_name NOT LIKE "%번역%")AND(saramin_data.company_name NOT LIKE "%석사%")AND(saramin_data.company_name NOT LIKE "%박사%")AND(saramin_data.company_name NOT LIKE "%코드잇%")AND(saramin_data.company_name NOT LIKE "%교육생%")AND(saramin_data.company_name NOT LIKE "%국비%")AND(saramin_data.company_name NOT LIKE "%청년수당%")AND(saramin_data.company_name NOT LIKE "%제약%")AND(saramin_data.company_name NOT LIKE "%건설%")AND(saramin_data.company_name NOT LIKE "%연구%")AND(saramin_data.company_name NOT LIKE "%기계%")AND(saramin_data.company_name NOT LIKE "%행정%")AND(saramin_data.company_name NOT LIKE "%호텔%")AND(saramin_data.company_name NOT LIKE "%천재교육%")AND(saramin_data.company_name NOT LIKE "%천재교과서%")AND(saramin_data.company_name NOT LIKE "%SeSAC%")AND(saramin_data.company_name NOT LIKE "%APM%")AND(saramin_data.company_name NOT LIKE "%apm%")AND(saramin_data.company_name NOT LIKE "%edi%")AND(saramin_data.company_name NOT LIKE "%EDI%")AND(saramin_data.company_name NOT LIKE "%개발자%")AND(saramin_data.company_name NOT LIKE "%시공%")AND(saramin_data.company_name NOT LIKE "%유튜브%")AND(saramin_data.company_name NOT LIKE "%양성%")))
AND (saramin_data.job_title NOT REGEXP 'pm[0-9]' AND saramin_data.job_title NOT REGEXP '[0-9]pm')
AND (company_name != prev_company)
UNION ALL
SELECT company, deadline, job_title, recruit_url, created_at, 'incruit' AS source_table
FROM (
    SELECT company, CASE 
        WHEN deadline = '-' THEN '상시' 
        ELSE deadline 
    END AS deadline, job_title, recruit_url, keywords, experience, created_at,
           LAG(company, 1) OVER (ORDER BY created_at DESC) AS prev_company
    FROM incruit
    WHERE (STR_TO_DATE(incruit.deadline, '%Y-%m-%d') > CURDATE() OR incruit.deadline = '상시' OR incruit.deadline = '채용시')
        AND (incruit.experience LIKE "신입%" OR incruit.experience = "신입/경력(연차무관)")
    ORDER BY created_at DESC
) AS incruit_data
WHERE (((incruit_data.job_title LIKE "%웹 기획%") OR (incruit_data.job_title LIKE "%앱 기획%") OR (incruit_data.job_title LIKE "%서비스 기획%") OR (incruit_data.job_title LIKE "%콘텐츠 기획%") OR (incruit_data.job_title LIKE "%전략 기획%") OR (incruit_data.job_title LIKE "%프로덕트 매니저%")) AND ((incruit_data.job_title NOT LIKE "%창업%")AND(incruit_data.job_title NOT LIKE "%번역%")AND(incruit_data.job_title NOT LIKE "%석사%")AND(incruit_data.job_title NOT LIKE "%박사%")AND(incruit_data.job_title NOT LIKE "%코드잇%")AND(incruit_data.job_title NOT LIKE "%교육생%")AND(incruit_data.job_title NOT LIKE "%국비%")AND(incruit_data.job_title NOT LIKE "%청년수당%")AND(incruit_data.job_title NOT LIKE "%제약%")AND(incruit_data.job_title NOT LIKE "%건설%")AND(incruit_data.job_title NOT LIKE "%연구%")AND(incruit_data.job_title NOT LIKE "%기계%")AND(incruit_data.job_title NOT LIKE "%행정%")AND(incruit_data.job_title NOT LIKE "%호텔%")AND(incruit_data.job_title NOT LIKE "%천재교육%")AND(incruit_data.job_title NOT LIKE "%천재교과서%")AND(incruit_data.job_title NOT LIKE "%SeSAC%")AND(incruit_data.job_title NOT LIKE "%APM%")AND(incruit_data.job_title NOT LIKE "%apm%")AND(incruit_data.job_title NOT LIKE "%edi%")AND(incruit_data.job_title NOT LIKE "%EDI%")AND(incruit_data.job_title NOT LIKE "%개발자%")AND(incruit_data.job_title NOT LIKE "%시공%")AND(incruit_data.job_title NOT LIKE "%유튜브%")AND(incruit_data.job_title NOT LIKE "%양성%")) AND ((incruit_data.company NOT LIKE "%창업%")AND(incruit_data.company NOT LIKE "%번역%")AND(incruit_data.company NOT LIKE "%석사%")AND(incruit_data.company NOT LIKE "%박사%")AND(incruit_data.company NOT LIKE "%코드잇%")AND(incruit_data.company NOT LIKE "%교육생%")AND(incruit_data.company NOT LIKE "%국비%")AND(incruit_data.company NOT LIKE "%청년수당%")AND(incruit_data.company NOT LIKE "%제약%")AND(incruit_data.company NOT LIKE "%건설%")AND(incruit_data.company NOT LIKE "%연구%")AND(incruit_data.company NOT LIKE "%기계%")AND(incruit_data.company NOT LIKE "%행정%")AND(incruit_data.company NOT LIKE "%호텔%")AND(incruit_data.company NOT LIKE "%천재교육%")AND(incruit_data.company NOT LIKE "%천재교과서%")AND(incruit_data.company NOT LIKE "%SeSAC%")AND(incruit_data.company NOT LIKE "%APM%")AND(incruit_data.company NOT LIKE "%apm%")AND(incruit_data.company NOT LIKE "%edi%")AND(incruit_data.company NOT LIKE "%EDI%")AND(incruit_data.company NOT LIKE "%개발자%")AND(incruit_data.company NOT LIKE "%시공%")AND(incruit_data.company NOT LIKE "%유튜브%")AND(incruit_data.company NOT LIKE "%양성%")))
AND (incruit_data.job_title NOT REGEXP 'pm[0-9]' AND incruit_data.job_title NOT REGEXP '[0-9]pm')
AND (company != prev_company)
UNION ALL
SELECT company_name, deadline, job_title, recruit_url, `date`, 'new_wanted' AS source_table
FROM (
    SELECT company_name, deadline, job_title, recruit_url, keywords, career, `date`,
           LAG(company_name, 1) OVER (ORDER BY `date` DESC) AS prev_company
    FROM new_wanted
    WHERE (STR_TO_DATE(new_wanted.deadline, '%Y-%m-%d') > CURDATE() OR new_wanted.deadline = '상시채용')
        AND (new_wanted.career LIKE "신입%")
    ORDER BY `date` DESC
) AS new_wanted_data
WHERE (((new_wanted_data.job_title LIKE "%웹 기획%") OR (new_wanted_data.job_title LIKE "%앱 기획%") OR (new_wanted_data.job_title LIKE "%서비스 기획%") OR (new_wanted_data.job_title LIKE "%콘텐츠 기획%") OR (new_wanted_data.job_title LIKE "%전략 기획%") OR (new_wanted_data.job_title LIKE "%프로덕트 매니저%")) AND ((new_wanted_data.job_title NOT LIKE "%창업%")AND(new_wanted_data.job_title NOT LIKE "%번역%")AND(new_wanted_data.job_title NOT LIKE "%석사%")AND(new_wanted_data.job_title NOT LIKE "%박사%")AND(new_wanted_data.job_title NOT LIKE "%코드잇%")AND(new_wanted_data.job_title NOT LIKE "%교육생%")AND(new_wanted_data.job_title NOT LIKE "%국비%")AND(new_wanted_data.job_title NOT LIKE "%청년수당%")AND(new_wanted_data.job_title NOT LIKE "%제약%")AND(new_wanted_data.job_title NOT LIKE "%건설%")AND(new_wanted_data.job_title NOT LIKE "%연구%")AND(new_wanted_data.job_title NOT LIKE "%기계%")AND(new_wanted_data.job_title NOT LIKE "%행정%")AND(new_wanted_data.job_title NOT LIKE "%호텔%")AND(new_wanted_data.job_title NOT LIKE "%천재교육%")AND(new_wanted_data.job_title NOT LIKE "%천재교과서%")AND(new_wanted_data.job_title NOT LIKE "%SeSAC%")AND(new_wanted_data.job_title NOT LIKE "%APM%")AND(new_wanted_data.job_title NOT LIKE "%apm%")AND(new_wanted_data.job_title NOT LIKE "%edi%")AND(new_wanted_data.job_title NOT LIKE "%EDI%")AND(new_wanted_data.job_title NOT LIKE "%개발자%")AND(new_wanted_data.job_title NOT LIKE "%시공%")AND(new_wanted_data.job_title NOT LIKE "%유튜브%")AND(new_wanted_data.job_title NOT LIKE "%양성%")) AND ((new_wanted_data.company_name NOT LIKE "%창업%")AND(new_wanted_data.company_name NOT LIKE "%번역%")AND(new_wanted_data.company_name NOT LIKE "%석사%")AND(new_wanted_data.company_name NOT LIKE "%박사%")AND(new_wanted_data.company_name NOT LIKE "%코드잇%")AND(new_wanted_data.company_name NOT LIKE "%교육생%")AND(new_wanted_data.company_name NOT LIKE "%국비%")AND(new_wanted_data.company_name NOT LIKE "%청년수당%")AND(new_wanted_data.company_name NOT LIKE "%제약%")AND(new_wanted_data.company_name NOT LIKE "%건설%")AND(new_wanted_data.company_name NOT LIKE "%연구%")AND(new_wanted_data.company_name NOT LIKE "%기계%")AND(new_wanted_data.company_name NOT LIKE "%행정%")AND(new_wanted_data.company_name NOT LIKE "%호텔%")AND(new_wanted_data.company_name NOT LIKE "%천재교육%")AND(new_wanted_data.company_name NOT LIKE "%천재교과서%")AND(new_wanted_data.company_name NOT LIKE "%SeSAC%")AND(new_wanted_data.company_name NOT LIKE "%APM%")AND(new_wanted_data.company_name NOT LIKE "%apm%")AND(new_wanted_data.company_name NOT LIKE "%edi%")AND(new_wanted_data.company_name NOT LIKE "%EDI%")AND(new_wanted_data.company_name NOT LIKE "%개발자%")AND(new_wanted_data.company_name NOT LIKE "%시공%")AND(new_wanted_data.company_name NOT LIKE "%유튜브%")AND(new_wanted_data.company_name NOT LIKE "%양성%")))
AND (new_wanted_data.job_title NOT REGEXP 'pm[0-9]' AND new_wanted_data.job_title NOT REGEXP '[0-9]pm')
AND (company_name != prev_company)
UNION ALL
SELECT company_name, deadline, job_title, recruit_url, `date`, 'jumpit' AS source_table
FROM (
    SELECT company_name, deadline, job_title, recruit_url, keywords, career, `date`,
           LAG(company_name, 1) OVER (ORDER BY `date` DESC) AS prev_company
    FROM jumpit
    WHERE (STR_TO_DATE(jumpit.deadline, '%Y-%m-%d') > CURDATE() OR jumpit.deadline = '상시')
        AND (jumpit.career LIKE "신입%")
    ORDER BY `date` DESC
) AS jumpit_data
WHERE (((jumpit_data.job_title LIKE "%웹 기획%") OR (jumpit_data.job_title LIKE "%앱 기획%") OR (jumpit_data.job_title LIKE "%서비스 기획%") OR (jumpit_data.job_title LIKE "%콘텐츠 기획%") OR (jumpit_data.job_title LIKE "%전략 기획%") OR (jumpit_data.job_title LIKE "%프로덕트 매니저%")) AND ((jumpit_data.job_title NOT LIKE "%창업%")AND(jumpit_data.job_title NOT LIKE "%번역%")AND(jumpit_data.job_title NOT LIKE "%석사%")AND(jumpit_data.job_title NOT LIKE "%박사%")AND(jumpit_data.job_title NOT LIKE "%코드잇%")AND(jumpit_data.job_title NOT LIKE "%교육생%")AND(jumpit_data.job_title NOT LIKE "%국비%")AND(jumpit_data.job_title NOT LIKE "%청년수당%")AND(jumpit_data.job_title NOT LIKE "%제약%")AND(jumpit_data.job_title NOT LIKE "%건설%")AND(jumpit_data.job_title NOT LIKE "%연구%")AND(jumpit_data.job_title NOT LIKE "%기계%")AND(jumpit_data.job_title NOT LIKE "%행정%")AND(jumpit_data.job_title NOT LIKE "%호텔%")AND(jumpit_data.job_title NOT LIKE "%천재교육%")AND(jumpit_data.job_title NOT LIKE "%천재교과서%")AND(jumpit_data.job_title NOT LIKE "%SeSAC%")AND(jumpit_data.job_title NOT LIKE "%APM%")AND(jumpit_data.job_title NOT LIKE "%apm%")AND(jumpit_data.job_title NOT LIKE "%edi%")AND(jumpit_data.job_title NOT LIKE "%EDI%")AND(jumpit_data.job_title NOT LIKE "%개발자%")AND(jumpit_data.job_title NOT LIKE "%시공%")AND(jumpit_data.job_title NOT LIKE "%유튜브%")AND(jumpit_data.job_title NOT LIKE "%양성%")) AND ((jumpit_data.company_name NOT LIKE "%창업%")AND(jumpit_data.company_name NOT LIKE "%번역%")AND(jumpit_data.company_name NOT LIKE "%석사%")AND(jumpit_data.company_name NOT LIKE "%박사%")AND(jumpit_data.company_name NOT LIKE "%코드잇%")AND(jumpit_data.company_name NOT LIKE "%교육생%")AND(jumpit_data.company_name NOT LIKE "%국비%")AND(jumpit_data.company_name NOT LIKE "%청년수당%")AND(jumpit_data.company_name NOT LIKE "%제약%")AND(jumpit_data.company_name NOT LIKE "%건설%")AND(jumpit_data.company_name NOT LIKE "%연구%")AND(jumpit_data.company_name NOT LIKE "%기계%")AND(jumpit_data.company_name NOT LIKE "%행정%")AND(jumpit_data.company_name NOT LIKE "%호텔%")AND(jumpit_data.company_name NOT LIKE "%천재교육%")AND(jumpit_data.company_name NOT LIKE "%천재교과서%")AND(jumpit_data.company_name NOT LIKE "%SeSAC%")AND(jumpit_data.company_name NOT LIKE "%APM%")AND(jumpit_data.company_name NOT LIKE "%apm%")AND(jumpit_data.company_name NOT LIKE "%edi%")AND(jumpit_data.company_name NOT LIKE "%EDI%")AND(jumpit_data.company_name NOT LIKE "%개발자%")AND(jumpit_data.company_name NOT LIKE "%시공%")AND(jumpit_data.company_name NOT LIKE "%유튜브%")AND(jumpit_data.company_name NOT LIKE "%양성%")))
AND (jumpit_data.job_title NOT REGEXP 'pm[0-9]' AND jumpit_data.job_title NOT REGEXP '[0-9]pm')
AND (company_name != prev_company);
